server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
  healthcheck:
    enabled: true # 启用健康检查,注意:需要引用spring boot actuator

spring:
  application:
    name: uaa

#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 通过属性更改负载均衡规则



swagger:
  enable: true